spring.application.name=usage-service
service.port=8083

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.type.mapping=energyUsageEvent:com.nev.ingestion_service.kafka.event.EnergyUsageEvent

